function [fitresult, gof] = createFit(TEs, Data)
%CREATEFIT(TES,DATASL2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : TEs
%      Y Output: DataSl2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-May-2014 16:43:00


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( TEs, Data );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [14365.0580734423 -0.00972216208509052];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
CVals = coeffvalues(fitresult);
M0 = CVals(1);neginvT2 = CVals(2);T2 = -1/neginvT2;
myfitinfo = ['T2 =',num2str(T2),'M0 =',num2str(M0)];
% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Data vs. TE', 'untitled fit 1', 'Location', 'NorthEast' );
text(10,10000,myfitinfo,'BackgroundColor',[.7 .9 .7]);
% Label axes
xlabel( 'TE (msec)' );
ylabel( 'Data' );
grid on


