function [fitresult, gof] = createFit(myTEs, myDat)
%CREATEFIT(MYTES,MYDAT)
%  Create a fit.
%
%  Data for 'Exp1' fit:
%      X Input : myTEs
%      Y Output: myDat
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Apr-2014 17:49:47


%% Fit: 'Exp1'.
[xData, yData] = prepareCurveData( myTEs, myDat );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [12986.9125442292 -0.242171317822978];
opts.Upper = [Inf Inf];
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Exp1' );
h = plot( fitresult, xData, yData );
legend( h, 'myDat vs. myTEs', 'Exp1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'myTEs' );
ylabel( 'myDat' );
grid on


